version: "3.7"
services:
    oweather-api:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: oweather-api
        restart: unless-stopped
        ports:
            - "8099:80"
        volumes:
            - ./:/app
        networks:
            - oweather_net

networks:
    oweather_net:
        driver: bridge
